name: container-images

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]

jobs:
  build-container-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1

    - run: echo "IMAGE_TAG=latest" >> $GITHUB_ENV
      if: github.ref_name == 'main'
    - run: echo "IMAGE_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
      if: startsWith(github.ref, 'refs/tags/v')

    - name: Login to ghcr.io
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - run: |
        ghcr.io/${{ github.repository }}:${{ env.IMAGE_TAG }}
