name: container-images


on:
  push:
    branches: [ "*" ]
    tags: [ "v*" ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - run: echo "IMAGE_TAG=dev" >> $GITHUB_ENV
      if: github.ref_name == 'main'
    - run: echo "IMAGE_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
      if: startsWith(github.ref, 'refs/tags/v')
    - run: echo ${{ env.IMAGE_TAG }}
    - run: echo ${{ github.ref_name }}
